-- --------------------------------------------------------
-- Хост:                         127.0.0.1
-- Версия сервера:               10.6.11-MariaDB-0ubuntu0.22.04.1 - Ubuntu 22.04
-- Операционная система:         debian-linux-gnu
-- HeidiSQL Версия:              12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Дамп структуры для таблица master_v_balashihe.draft_blog_article
CREATE TABLE IF NOT EXISTS `draft_blog_article` (
  `draftArticleId` binary(16) NOT NULL DEFAULT unhex(replace(uuid(),'-','')),
  `handle` text CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `title` text DEFAULT NULL,
  `autoHandleSlug` text CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `blogCategoryId` int(10) unsigned DEFAULT NULL,
  `text` mediumtext DEFAULT NULL,
  `textHtml` mediumtext DEFAULT NULL,
  `textRawDraftContentState` mediumtext DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `updatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `publishedAt` timestamp NULL DEFAULT NULL,
  `published` tinyint(1) unsigned DEFAULT 1,
  `orderNumber` int(10) unsigned DEFAULT NULL,
  `managerId` int(10) unsigned NOT NULL,
  `existingArticleId` int(10) unsigned DEFAULT NULL,
  `isDraftSaved` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`draftArticleId`) USING BTREE,
  KEY `FK_draft_blog_article_blog_category` (`blogCategoryId`),
  KEY `FK_draft_blog_article_managers` (`managerId`),
  KEY `FK_draft_blog_article_blog_article` (`existingArticleId`) USING BTREE,
  CONSTRAINT `FK_draft_blog_article_blog_article` FOREIGN KEY (`existingArticleId`) REFERENCES `blog_article` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_draft_blog_article_blog_category` FOREIGN KEY (`blogCategoryId`) REFERENCES `blog_category` (`blogCategoryId`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `FK_draft_blog_article_managers` FOREIGN KEY (`managerId`) REFERENCES `managers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Дамп данных таблицы master_v_balashihe.draft_blog_article: ~55 rows (приблизительно)
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x122ba158ae4311ed83e960a44c4f528e, NULL, 'sadfadsf sadf', 'sadfadsf-sadf', NULL, 'sdfsdfsdfsdfsa  sadfdsfasdfdsf', '<p>sdfsdfsdfsdfsa&nbsp; sadfdsfasdfdsf</p>', NULL, '2023-02-16 21:44:24', '2023-02-16 21:44:32', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x12753a48ae3d11ed83e960a44c4f528e, NULL, 'dfsdfsdfewrewrfeasdfdsafdsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', 'dfsdfsdfewrewrfeasdfdsafdsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', NULL, 'sadfsdfsdferewrer  ewrewr ewrewr', '<p>sadfsdfsdferewrer&nbsp; ewrewr ewrewr</p>', NULL, '2023-02-16 21:01:27', '2023-02-16 21:01:27', NULL, NULL, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x1de39beaae5211ed83e960a44c4f528e, NULL, 'adsadsad dsfsdf', 'adsadsad-dsfsdf', NULL, 'sdfdsfdsfsdf sdfsdfsd ', '<p>sdfdsfdsfsdf sdfsdfsd&nbsp;</p>', NULL, '2023-02-16 23:32:06', '2023-02-16 23:32:06', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x1ea78083ae4011ed83e960a44c4f528e, NULL, 'sadfadsf sadf df', 'sadfadsf-sadf-df', NULL, 'sdfsdfsdfsdfsddd dfdsf', '<p>sdfsdfsdfsdfsddd dfdsf</p>', NULL, '2023-02-16 21:23:16', '2023-02-16 21:23:16', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x1f5d9f61b22411ed99fd00155dc6f497, NULL, 'fdsdfsd', 'fdsdfsd', NULL, 'ewrewrwer', '<p>ewrewrwer</p>', NULL, '2023-02-21 20:45:39', '2023-02-21 21:45:25', NULL, NULL, NULL, 1, 17, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x20c3aa9cae5211ed83e960a44c4f528e, NULL, 'adsadsad dsfsdf', 'adsadsad-dsfsdf', NULL, 'sdfdsfdsfsdf sdfsdfsd  sdfsdf ', '<p>sdfdsfdsfsdf sdfsdfsd&nbsp; sdfsdf&nbsp;</p>', NULL, '2023-02-16 23:32:10', '2023-02-16 23:32:11', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x2317a44aae4311ed83e960a44c4f528e, NULL, 'sadfadsf sadf', 'sadfadsf-sadf', NULL, 'sdfsdfsdfsdfsa  sadfdsfasdfdsf\n\n\n\n\n\n', '<p>sdfsdfsdfsdfsa&nbsp; sadfdsfasdfdsf</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>', NULL, '2023-02-16 21:44:52', '2023-02-16 21:57:56', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x236c7e3eae5211ed83e960a44c4f528e, NULL, 'adsadsad dsfsdf sdafsdfds', 'adsadsad-dsfsdf-sdafsdfds', NULL, 'sdfdsfdsfsdf sdfsdfsd  sdfsdf ', '<p>sdfdsfdsfsdf sdfsdfsd&nbsp; sdfsdf&nbsp;</p>', NULL, '2023-02-16 23:32:15', '2023-02-16 23:32:15', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x23c5c831ae4f11ed83e960a44c4f528e, NULL, 'ewrewrwerewr', 'ewrewrwerewr', NULL, 'sdafdsfsdfsd', '<p>sdafdsfsdfsd</p>', NULL, '2023-02-16 23:10:47', '2023-02-16 23:11:25', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x264f6a2bae1111ed83e960a44c4f528e, NULL, 'sadddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', 'sadddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', NULL, 'sadfsdfsdf\n\n', '<p>sadfsdfsdf</p>\n<p>&nbsp;</p>', NULL, '2023-02-16 15:47:02', '2023-02-16 19:16:15', NULL, 1, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x27d0a6b3ae5211ed83e960a44c4f528e, NULL, 'adsadsad dsfsdf sdafsdfds', 'adsadsad-dsfsdf-sdafsdfds', NULL, 'sdfdsfdsfsdf sdfsdfsd  sdfsdf   sdafdf    ', '<p>sdfdsfdsfsdf sdfsdfsd&nbsp; sdfsdf&nbsp; &nbsp;sdafdf&nbsp; &nbsp;&nbsp;</p>', NULL, '2023-02-16 23:32:22', '2023-02-16 23:32:22', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x5110bf69ae4a11ed83e960a44c4f528e, NULL, 'sadsadasd', 'sadsadasd', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdsfasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdsfasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:36:16', '2023-02-16 22:45:43', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x52ce9ecbae4e11ed83e960a44c4f528e, NULL, 'asfddsf', 'asfddsf', NULL, 'sdfdsfds', '<p>sdfdsfds</p>', NULL, '2023-02-16 23:04:56', '2023-02-16 23:04:57', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x5d89959fae3d11ed83e960a44c4f528e, NULL, 'dfsdfsdfewrewrfeasdfdsafdsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', 'dfsdfsdfewrewrfeasdfdsafdsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', NULL, 'sdfsdfsdfsdf', '<p>sdfsdfsdfsdf</p>', NULL, '2023-02-16 21:03:33', '2023-02-16 21:03:33', NULL, NULL, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x613e9057b20f11ed99fd00155dc6f497, NULL, '323232', '323232', NULL, '324324', '<p>324324</p>', NULL, '2023-02-21 17:51:06', '2023-02-21 17:51:08', NULL, NULL, NULL, 1, 16, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x62c1347bad7d11edabd260a44c4f528e, NULL, '1', '1', NULL, '0', '<p>0</p>', NULL, '2023-02-15 22:09:15', '2023-02-15 22:33:45', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x63b601f2abea11edbbfd60a44c4f528e, NULL, 'dfsdfsdf', 'dfsdfsdf', NULL, 'sadfsdfsdf', '<p>sadfsdfsdf</p>', NULL, '2023-02-13 22:04:32', '2023-02-13 22:04:34', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x64a5d2f3ae5511ed83e960a44c4f528e, NULL, '11 adsadsad dsfsdf sdafsdfds', '11-adsadsad-dsfsdf-sdafsdfds', NULL, 'sdfdsfdsfsdf sdfsdfsd  sdfsdf   sdafdf    ', '<p>sdfdsfdsfsdf sdfsdfsd&nbsp; sdfsdf&nbsp; &nbsp;sdafdf&nbsp; &nbsp;&nbsp;</p>', NULL, '2023-02-16 23:55:33', '2023-02-16 23:55:36', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x69566a39ae5511ed83e960a44c4f528e, NULL, '11 adsadsad dsfsdf sdafsdfds', '11-adsadsad-dsfsdf-sdafsdfds', NULL, '22sdfdsfdsfsdf sdfsdfsd  sdfsdf   sdafdf    ', '<p>22sdfdsfdsfsdf sdfsdfsd&nbsp; sdfsdf&nbsp; &nbsp;sdafdf&nbsp; &nbsp;&nbsp;</p>', NULL, '2023-02-16 23:55:41', '2023-02-16 23:55:41', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x7943cf59abea11edbbfd60a44c4f528e, NULL, 'dfsdfsdfewrewr', 'dfsdfsdfewrewr', NULL, 'sadfsdfsdf', '<p>sadfsdfsdf</p>', NULL, '2023-02-13 22:05:08', '2023-02-13 22:05:08', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x8574c301abd211edbbfd60a44c4f528e, NULL, 'sdafsdfdssadf', 'sdafsdfdssadf', NULL, '11', '<ul>\n<li>11</li>\n</ul>', NULL, '2023-02-13 19:13:40', '2023-02-13 20:12:53', NULL, 1, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x87b305d9ae5511ed83e960a44c4f528e, NULL, '11 adsadsad dsfsdf sdafsdfds dssdaf dsf  dddsse das                dddddddddddddddddddddddddddddddd', '11-adsadsad-dsfsdf-sdafsdfds-dssdaf-dsf-dddsse-das-dddddddddddddddddddddddddddddddd', NULL, '22sdfdsfdsfsdf sdfsdfsd  sdfsdf   sdafdf    \n\ndddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\n\nddd\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nsdfg\n\n\n\nfdgfdg sdkjfid jsdfk eiwlskdkdka; dsd', '<p>22sdfdsfdsfsdf sdfsdfsd&nbsp; sdfsdf&nbsp; &nbsp;sdafdf&nbsp; &nbsp;&nbsp;</p>\n<p>dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd</p>\n<p>ddd</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>sdfg</p>\n<p>&nbsp;</p>\n<p>fdgfdg sdkjfid jsdfk eiwlskdkdka; dsd</p>', NULL, '2023-02-16 23:56:32', '2023-02-16 23:56:52', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x8827d19cb20f11ed99fd00155dc6f497, NULL, '33323232', '33323232', NULL, '324324', '<p>324324</p>', NULL, '2023-02-21 17:52:11', '2023-02-21 17:52:11', NULL, NULL, NULL, 1, 16, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x891a1166abd111edbbfd60a44c4f528e, NULL, 'sdafsdfdssdf', 'sdafsdfdssdf', NULL, '11', '<ul>\n<li>11</li>\n</ul>', NULL, '2023-02-13 19:06:37', '2023-02-13 19:06:37', NULL, 1, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x8c29e28fabd111edbbfd60a44c4f528e, NULL, 'sdafsdfds243', 'sdafsdfds243', NULL, '11', '<ul>\n<li>11</li>\n</ul>', NULL, '2023-02-13 19:06:42', '2023-02-13 19:13:35', NULL, 1, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x941cc735abea11edbbfd60a44c4f528e, NULL, 'dfsdfsdfewrewrfeeee', 'dfsdfsdfewrewrfeeee', NULL, 'sadfsdfsdf', '<p>sadfsdfsdf</p>', NULL, '2023-02-13 22:05:53', '2023-02-13 22:06:34', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0x9cc35fe9abe711edbbfd60a44c4f528e, NULL, 'dfsdfs', 'dfsdfs', NULL, 'sdfsdfsdf', '<p>sdfsdfsdf</p>', NULL, '2023-02-13 21:44:39', '2023-02-13 21:44:41', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xa4874264ae3611ed83e960a44c4f528e, NULL, 'dfsdfsdfewrewrfewreweeeeeeeeeeeewererqererwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', 'dfsdfsdfewrewrfewreweeeeeeeeeeeewererqererwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', NULL, 'sadfsdfsdferewrer  ewrewr ewrewr', '<p>sadfsdfsdferewrer&nbsp; ewrewr ewrewr</p>', NULL, '2023-02-16 20:15:26', '2023-02-16 20:15:38', NULL, NULL, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xa558146eae4e11ed83e960a44c4f528e, NULL, 'sdfdsfds', 'sdfdsfds', NULL, 'hjhjkhksdfsdfdsf', '<p>hjhjkhksdfsdfdsf</p>', NULL, '2023-02-16 23:07:15', '2023-02-16 23:07:18', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xa63deeb8ae4011ed83e960a44c4f528e, NULL, 'sadfadsf sadfddd', 'sadfadsf-sadfddd', NULL, 'sdfsdfsdfsdfsddd dfdsf', '<p>sdfsdfsdfsdfsddd dfdsf</p>', NULL, '2023-02-16 21:27:03', '2023-02-16 21:27:04', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xa65a0ba3b20f11ed99fd00155dc6f497, NULL, '33323232', '33323232', NULL, 'aa324324', '<p>aa324324</p>', NULL, '2023-02-21 17:53:02', '2023-02-21 17:53:02', NULL, NULL, NULL, 1, 16, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xa809b45ead7a11edabd260a44c4f528e, NULL, 'dfsdfsdfewrewrfee   eedd3232', 'dfsdfsdfewrewrfee-eedd3232', NULL, '12\n\n', '<p>12</p>\n<p>&nbsp;</p>', NULL, '2023-02-15 21:49:43', '2023-02-16 15:26:03', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xa9041e6bae4011ed83e960a44c4f528e, NULL, 'sadfadsf sadfsdasdas', 'sadfadsf-sadfsdasdas', NULL, 'sdfsdfsdfsdfsddd dfdsf', '<p>sdfsdfsdfsdfsddd dfdsf</p>', NULL, '2023-02-16 21:27:08', '2023-02-16 21:27:08', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xaa37443aae4b11ed83e960a44c4f528e, NULL, 'sdasdasds', 'sdasdasds', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdsfasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdsfasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:45:55', '2023-02-16 22:46:44', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xab7a27a0ae4011ed83e960a44c4f528e, NULL, 'sadfadsf sadfdssadsad', 'sadfadsf-sadfdssadsad', NULL, 'sdfsdfsdfsdfsddd dfdsf', '<p>sdfsdfsdfsdfsddd dfdsf</p>', NULL, '2023-02-16 21:27:12', '2023-02-16 21:27:12', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xac736292abea11edbbfd60a44c4f528e, NULL, 'dfsdfsdfewrewrfeeeedd', 'dfsdfsdfewrewrfeeeedd', NULL, 'sadfsdfsdf', '<p>sadfsdfsdf</p>', NULL, '2023-02-13 22:06:34', '2023-02-13 22:07:25', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xaf5e8a28ae3f11ed83e960a44c4f528e, NULL, 'dfsdfsdfewrewrfeasdfdsafddssdfsdfdsfsdfsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', 'dfsdfsdfewrewrfeasdfdsafddssdfsdfdsfsdfsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', NULL, 'sdfsdfsdfsdfsddd dfdsf', '<p>sdfsdfsdfsdfsddd dfdsf</p>', NULL, '2023-02-16 21:20:09', '2023-02-16 21:20:09', NULL, NULL, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xb53c1de6ae3d11ed83e960a44c4f528e, NULL, 'dfsdfsdfewrewrfeasdfdsafddssdfsdfdsfsdfsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', 'dfsdfsdfewrewrfeasdfdsafddssdfsdfdsfsdfsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', NULL, 'sdfsdfsdfsdfsd', '<p>sdfsdfsdfsdfsd</p>', NULL, '2023-02-16 21:06:00', '2023-02-16 21:06:35', NULL, NULL, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xb6263d4dae4011ed83e960a44c4f528e, NULL, 'sadfadsf sadf', 'sadfadsf-sadf', NULL, 'fdsdfdsfsdafa  sdafdsf  ', '<p>fdsdfdsfsdafa&nbsp; sdafdsf&nbsp;&nbsp;</p>', NULL, '2023-02-16 21:27:30', '2023-02-16 21:44:24', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xb864c3c9ae4f11ed83e960a44c4f528e, NULL, 'adsadsad', 'adsadsad', NULL, 'sdfdsfdsfsdf', '<p>sdfdsfdsfsdf</p>', NULL, '2023-02-16 23:14:56', '2023-02-16 23:15:36', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xbd179e43ae4911ed83e960a44c4f528e, NULL, 'sadfdsfsdf', 'sadfdsfsdf', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdsfasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdsfasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:32:07', '2023-02-16 22:32:10', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xbfeb158fae4911ed83e960a44c4f528e, NULL, 'dsadsadsa', 'dsadsadsa', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdsfasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdsfasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:32:12', '2023-02-16 22:35:51', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xc3ddf531ae4711ed83e960a44c4f528e, NULL, 'ssdf', 'ssdf', NULL, 'sdfdsfsdffsaf', '<ol>\n<li>sdfdsfsdffsaf</li>\n</ol>', NULL, '2023-02-16 22:18:00', '2023-02-16 22:18:05', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xc8c7ee74ae4711ed83e960a44c4f528e, NULL, 'sadfdsfds', 'sadfdsfds', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdssdfdsf \n\n\n\nsdfsdfsdf dsfdsfd                                       fasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdssdfdsf&nbsp;</li>\n<li>&nbsp;</li>\n<li>&nbsp;</li>\n<li>&nbsp;</li>\n<li>sdfsdfsdf dsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;fasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:18:08', '2023-02-16 22:32:04', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xccf4274dae4b11ed83e960a44c4f528e, NULL, 'sdcadasdsad', 'sdcadasdsad', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdsfasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdsfasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:46:53', '2023-02-16 22:46:53', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xce8a136eae3f11ed83e960a44c4f528e, NULL, 'sadfadsf sadf', 'sadfadsf-sadf', NULL, 'sdfsdfsdfsdfsddd dfdsf', '<p>sdfsdfsdfsdfsddd dfdsf</p>', NULL, '2023-02-16 21:21:02', '2023-02-16 21:21:02', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xcf07f9feae4b11ed83e960a44c4f528e, NULL, 'sdsadsdas', 'sdsadsdas', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdsfasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdsfasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:46:56', '2023-02-16 22:46:57', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xd0991073ae4b11ed83e960a44c4f528e, NULL, 'dsdsdsadsad', 'dsdsdsadsad', NULL, 'sdfdsfsdffsafsdfsdf dsfdsfdsfd                                   sdfdsfasdf                                       ', '<ol>\n<li>sdfdsfsdffsafsdfsdf dsfdsfdsfd&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;sdfdsfasdf&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li>\n</ol>', NULL, '2023-02-16 22:46:59', '2023-02-16 22:47:30', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xd4e9088eabe711edbbfd60a44c4f528e, NULL, 'sdfsdf', 'sdfsdf', NULL, 'sadfsdfsdf', '<p>sadfsdfsdf</p>', NULL, '2023-02-13 21:46:13', '2023-02-13 21:46:19', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xd6f09920ae5511ed83e960a44c4f528e, NULL, '11 adsadsad dsfsdf sdafsdfds dssdaf dsf  dddsse das                dddddddddddddddddddddddddddddddd', '11-adsadsad-dsfsdf-sdafsdfds-dssdaf-dsf-dddsse-das-dddddddddddddddddddddddddddddddd', NULL, '2 22sdfdsfdsfsdf sdfsdfsd  sdfsdf   sdafdf    \n\ndddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\n\nddd\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nsdfg\n\n\n\nfdgfdg sdkjfid jsdfk eiwlskdkdka; dsd', '<p>2 22sdfdsfdsfsdf sdfsdfsd&nbsp; sdfsdf&nbsp; &nbsp;sdafdf&nbsp; &nbsp;&nbsp;</p>\n<p>dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd</p>\n<p>ddd</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<p>sdfg</p>\n<p>&nbsp;</p>\n<p>fdgfdg sdkjfid jsdfk eiwlskdkdka; dsd</p>', NULL, '2023-02-16 23:58:45', '2023-02-16 23:58:45', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xe5b4e3bcae4e11ed83e960a44c4f528e, NULL, 'sdfdsfdsf', 'sdfdsfdsf', NULL, 'dsfdsfdfdsf', '<p>dsfdsfdfdsf</p>', NULL, '2023-02-16 23:09:03', '2023-02-16 23:09:05', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xe7c2fb6eabda11edbbfd60a44c4f528e, NULL, 'sdafsdfdssadfee', 'sdafsdfdssadfee', NULL, '11', '<ul>\n<li>11</li>\n</ul>', NULL, '2023-02-13 20:13:41', '2023-02-13 20:13:41', NULL, 1, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xe9cba577ae3d11ed83e960a44c4f528e, NULL, 'dfsdfsdfewrewrfeasdfdsafddssdfsdfdsfsdfsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', 'dfsdfsdfewrewrfeasdfdsafddssdfsdfdsfsdfsafwdddddddddddddddddddddddddddddddasfasdfdsfreweeeddddddddddddddddddddddddddddeeeeeeeeewererqerersadfdsafwreeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedsfsdafadsfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewerwerwerewr', NULL, 'sdfsdfsdfsdfsddd', '<p>sdfsdfsdfsdfsddd</p>', NULL, '2023-02-16 21:07:28', '2023-02-16 21:07:28', NULL, NULL, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xeb3a5667abda11edbbfd60a44c4f528e, NULL, 'sdafsdfdssadfeeasdf', 'sdafsdfdssadfeeasdf', NULL, '11', '<ul>\n<li>11</li>\n</ul>', NULL, '2023-02-13 20:13:47', '2023-02-13 20:13:47', NULL, 1, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xf36d2fcdae4b11ed83e960a44c4f528e, NULL, 'sdasdsadsa', 'sdasdsadsa', NULL, 'afddfdfsdfsdf', '<p>afddfdfsdfsdf</p>', NULL, '2023-02-16 22:47:57', '2023-02-16 23:04:52', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xf378457ca71d11ed8cee60a44c4f528e, NULL, 'sdafsdfds', 'sdafsdfds', NULL, '11', '<ul>\n<li>11</li>\n</ul>', NULL, '2023-02-07 19:31:02', '2023-02-13 19:01:28', NULL, 1, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xf5e956ccabea11edbbfd60a44c4f528e, NULL, 'dfsdfsdfewrewrfeeeedd3232', 'dfsdfsdfewrewrfeeeedd3232', NULL, 'sadfsdfsdf', '<p>sadfsdfsdf</p>', NULL, '2023-02-13 22:08:37', '2023-02-13 22:08:37', NULL, NULL, NULL, 1, NULL, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xfc869142ae5111ed83e960a44c4f528e, NULL, 'adsadsad', 'adsadsad', NULL, 'sdfdsfdsfsdf sdfsdfsd ', '<p>sdfdsfdsfsdf sdfsdfsd&nbsp;</p>', NULL, '2023-02-16 23:31:10', '2023-02-16 23:31:10', NULL, 1, NULL, 1, 11, 1);
INSERT IGNORE INTO `draft_blog_article` (`draftArticleId`, `handle`, `title`, `autoHandleSlug`, `blogCategoryId`, `text`, `textHtml`, `textRawDraftContentState`, `createdAt`, `updatedAt`, `publishedAt`, `published`, `orderNumber`, `managerId`, `existingArticleId`, `isDraftSaved`) VALUES
	(_binary 0xfd4c5908ae4411ed83e960a44c4f528e, NULL, 'dsfdsfds', 'dsfdsfds', NULL, 'sdfdsfsdffsaf', '<p>sdfdsfsdffsaf</p>', NULL, '2023-02-16 21:58:08', '2023-02-16 22:17:50', NULL, 1, NULL, 1, 11, 1);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
